trigger:
- main

pool:
vmImage: 'ubuntu-latest'

steps:
- task: Gradle@3
inputs:
gradleWrapperFile: 'gradlew'
tasks: 'clean test'
publishJUnitResults: true
testResultsFiles: '**/TEST-*.xml'
javaHomeOption: 'JDKVersion'
jdkVersionOption: '21'
jdkArchitectureOption: 'x64'